#todo 需要自己修改的地方
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: reggie_take_out

    #todo 需要自己修改的地方
  profiles:
    active: dev
#    #todo 需要自己修改的地方(没必要的地方不用配置,配置在后面的文件中)
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 78787899
  #todo 需要自己修改的地方
  mail:
    host: smtp.qq.com
    username: 1847527975@qq.com
    password: dajrikrhgymiejdf
    properties:
      mail:
        smtp:
          enable: true
    default-encoding: UTF-8

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID # 主键类型  AUTO->`数据库ID自增` INPUT->`用户输入ID` ASSIGN_ID->`分配ID` (数字类型唯一ID) ASSIGN_UUID->`分配UUID` (字符串类型UUID)
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

